apiVersion: v1
kind: Namespace
metadata:
  name: {{.Namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.AppName}}-deployment
  namespace: {{.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.AppName}}
  template:
    metadata:
      labels:
        app: {{.AppName}}
    spec:
      serviceAccountName: cluster-admin
      containers:
      - name: {{.AppName}}
        # image: "harbor.katana.local/katana/"{{.Image}}
        image: "iiteens/"{{.Image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{.AppName}}-svc
  namespace: {{.Namespace}}
spec:
  selector:
    app: {{.AppName}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
