apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: kube-system
data:
# To add in setup script: systemctl restart containerd &&
  setup.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates &&
    if grep -q "harbor.katana.local" /etc/hosts; then
      echo "Updating entry in /etc/hosts"
      current_ip=$(grep "harbor.katana.local" /etc/hosts | awk '{print $1}')
      new_ip="{{.HarborIP}}"
      sed -i "s/$current_ip/$new_ip/" /etc/hosts
    else
      echo "Adding entry to /etc/hosts"
      echo "{{.HarborIP}}  harbor.katana.local" >> /etc/hosts
    fi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-custom-setup
  namespace: kube-system
  labels:
    k8s-app: node-custom-setup
spec:
  selector:
    matchLabels:
      k8s-app: node-custom-setup
  template:
    metadata:
      labels:
        k8s-app: node-custom-setup
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: init-node
          command: ["nsenter"]
          args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
          image: debian
          env:
            - name: TRUSTED_CERT
              valueFrom:
                configMapKeyRef:
                  name: trusted-ca
                  key: ca.crt
            - name: SETUP_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: setup-script
                  key: setup.sh
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
