kubeconfig = ""
kubehost = "0.0.0.0"
backendurl = "http://192.168.49.1:3000"
rootdirectory = "/opt/katana"
kubenamespace = "default"
timeout = 20
numberofdeployments = 1

[cluster]
deploymentlabel = "katana"
teamcount = 1
teamlabel = "ctfteam"
templated_manifest_dir = "kubernetes/templates"
templated_manifests = [
    "harbor.yml",
]

[services.api]
host = "0.0.0.0"
port = 3000

[services.challengedeployer]
host = "challengedeployer.katana.local"
port = 8002
teamclientport = 3004

[teamvm]
teampodname = "katana-team-master-pod"
containername = "teamvm"
challengedir = "/opt/challenges/"
tmpdir = "/tmp/"
initfile = "run.sh"
daemonport = 3004

[services.sshprovider]
host = "0.0.0.0"
port = 2222
creds_file = "teamcreds.txt"
password_length = 10

[mongo]
username = "adminuser"
password = "password123"
port = "32000"
mongosh_version = "1.6.1"
cluster_url = "challengedeployer.katana.local"

[mysql]
username = "root"
password = "test1234"
port = "32001"

[admin]
username = "sdslabs"
password = "sdslabs"

[harbor]
username = "admin"
password = "Password12345" # NOTE: Password should be 8-128 characters long with at least 1 uppercase, 1 lowercase and 1 number
hostname = "harbor.katana.local"
