[services.api]
host = "localhost"
port = 3000

[services.vmdeployer]
host = "localhost"
port = 8001

[services.challengedeployer]
host = "localhost"
port = 8002
kubeconfig = ""
kubehost = "localhost"
kubenamespace = ""
broadcastport = 3003
teamlabel = "ctfteam"