kubeconfig = ""
kubehost = "http://localhost"
kubenamespace = ""

[services.api]
host = "localhost"
port = 3000

[services.vmdeployer]
host = "localhost"
port = 8001

[services.challengedeployer]
host = "localhost"
port = 8002
broadcastport = 3003
teamclientport = 2002
teamlabel = "ctfteam"
