kubeconfig = ""
kubehost = "http://localhost"
kubenamespace = "default"

[cluster]
broadcastcount = 2
broadcastlabel = "broadcast"
teamcount = 3
teamlabel = "ctfteam"
manifest_dir = "manifests/templates"
manifests = [
    "teams.yml",
    "broadcast.yml",
    "broadcast-service.yml",
    "elasticsearch_svc.yaml",
    "elasticsearch_statefulset.yaml",
    "kibana.yaml",
    "fluentd-daemonset.yaml",
    "ingress.yml"
]

[services.api]
host = "localhost"
port = 3000

[services.challengedeployer]
host = "challengedeployer.katana.local"
port = 8002
broadcastport = 3003
teamclientport = 3004
challengeartifactlabel = "challfile"

[teamvm]
challengedir = "/opt/challenges/"
tmpdir = "/tmp/"
initfile = "run.sh"
daemonport = 3004