kubeconfig = ""
kubehost = "http://localhost"
kubenamespace = "default"
verbosity = 3

[cluster]
deploymentlabel = "katana"
broadcastcount = 2
broadcastlabel = "broadcast"
teamcount = 3
teamlabel = "ctfteam"
manifest_dir = "manifests/templates"
manifests = [
    "teams.yml",
    "broadcast.yml",
    "broadcast-service.yml",
    "ingress.yml",
    "openvpn.yml",
    "es-sts.yml",
    "es-svc.yml",
    "fluentd-ds.yml",
    "fluentd-rb.yml",
    "fluentd-role.yml",
    "fluentd-sa.yml",
    "kibana-deployment.yml",
    "kibana-svc.yml"
]

[services.api]
host = "localhost"
port = 3000

[services.challengedeployer]
host = "challengedeployer.katana.local"
port = 8002
broadcastport = 3003
teamclientport = 3004
challengeartifactlabel = "challfile"

[teamvm]
challengedir = "/opt/challenges/"
tmpdir = "/tmp/"
initfile = "run.sh"
daemonport = 3004

[services.sshprovider]
host = "localhost"
port = 2222
creds_file = "teamcreds.txt"
password_length = 10

[mongo]
url = "mongodb://scar:scar@localhost:27017/?authSource=admin"

[admin]
username = "sdslabs"
password = "sdslabs"
