kubeconfig = ""
kubehost = "http://localhost"
kubenamespace = "default"

[cluster]
broadcastcount = 2
broadcastlabel = "broadcast"
teamcount = 3
teamlabel = "ctfteam"
manifest_dir = "templates/manifests"
manifests = [
    "teams.yml",
    "broadcast.yml",
    "broadcast-service.yml"
]

[services.api]
host = "localhost"
port = 3000

[services.challengedeployer]
host = "localhost"
port = 8002
broadcastport = 3003
teamclientport = 3004
challenge_artifact_label = "challfile"
