kubeconfig = ""
kubehost = "http://localhost"
kubenamespace = ""

[cluster]
broadcastcount = 2
broadcastlabel = "broadcast"
teamcount = 3
teamlabel = "ctfteam"

[services.api]
host = "localhost"
port = 3000

[services.challengedeployer]
host = "localhost"
port = 8002
broadcastport = 3003
teamclientport = 3004
