apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command:
      - sleep
      - "3600"
    resources:
      limits:
        memory: "256Mi"
        cpu: "0.5"
