apiVersion: v1
kind: Service
metadata:
  name: broadcast-service
spec:
  type: NodePort
  selector:
    app: {{.BroadcastLabel}}
  ports:
    - protocol: TCP
      port: {{.BroadcastPort}}
      targetPort: {{.BroadcastPort}}
