apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-role
  namespace: katana
rules:
- apiGroups: ["apps"]
  resources: ["pods", "pods/exec", "services", "statefulsets","statefulsets/scale"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
  namespace: katana
subjects:
- kind: ServiceAccount
  name: cluster-admin
  namespace: katana
roleRef:
  kind: ClusterRole
  name: cluster-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: katana
