apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: katana-ingress
spec:
  rules:
    - host: {{.ChallengeDeployerHost}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: broadcast-service
                port:
                  number: {{.BroadcastPort}}
